name: Days of Eternity
favicon: null
layout_spectrum: 0.49519
typography_spectrum: 0.41316
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#29abe1'
    - '#96bbd1'
    - '#7c423b'
    - '#ddf1f6'
    - '#00ffff'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
