name: Days of Eternity
favicon: null
layout_spectrum: 0.9957287970464677
typography_spectrum: 0.34708786802366376
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.15501748630777
  lightness: 0.7621513896156102
  saturation: 0.4294022263493389
  rhythmicContrast: 0.2292379611171782
purpose: []
