typography_spectrum: 0.41316
color:
  brandColors:
    - '#fe0000'
    - '#fdfffc'
    - '#090601'
    - '#008036'
    - '#95b76a'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.98977
analytics:
  google: null
  facebook: null
  twitter: null
name: Days of Eternity
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Memories
description: Fondness
purpose: []
