name: Days of Eternity
favicon: null
layout_spectrum: 0.98977
typography_spectrum: 0.41316
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fe0000'
    - '#fdfffc'
    - '#090601'
    - '#008036'
    - '#95b76a'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
