name: Days of Eternity
favicon: null
layout_spectrum: 0.98977
typography_spectrum: 0.41316
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#cb544e'
    - '#703d4c'
    - '#d18973'
    - '#4d0b00'
  brandStrength: 0.625
  lightness: 0.75
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
