name: Days of Eternity
favicon: null
layout_spectrum: 0.98977
typography_spectrum: 0.41316
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0a08'
    - '#c3b8b2'
    - '#efeef3'
    - '#38507c'
    - '#608d19'
  brandStrength: 0.125
  lightness: 0.25
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
