name: Days of Eternity
favicon: null
layout_spectrum: 0.0343
typography_spectrum: 0.03508
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#290d02'
    - '#59503f'
    - '#53c0e1'
    - '#d1c6bf'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
